/**
 Export to JSON plugin for PHPMyAdmin
 @version 4.6.3
 */

// Database 'Shorter'

// Shorter.entries

var interj = [{"word":"Ah"}, {"word":"Aha"}, {"word":"Ahem"}, {"word":"Ahey"}, {"word":"Ahoy"}, {"word":"Alack"}, {"word":"Alackaday"}, {"word":"Alas"}, {"word":"All hail"}, {"word":"Anan"}, {"word":"Aroint"}, {"word":"Aroynt"}, {"word":"Avaunt"}, {"word":"Ay"}, {"word":"Baccare"}, {"word":"Backare"}, {"word":"Backare"}, {"word":"Bah"}, {"word":"Basta"}, {"word":"Begone"}, {"word":"Bismillah"}, {"word":"Bo"}, {"word":"Bravo"}, {"word":"Clum"}, {"word":"Depardieux"}, {"word":"Egad"}, {"word":"Eh"}, {"word":"Eigh"}, {"word":"Enough"}, {"word":"Faith"}, {"word":"Farewell"}, {"word":"Faugh"}, {"word":"Fiddledeedee"}, {"word":"Fie"}, {"word":"Foh"}, {"word":"Fugh"}, {"word":"Fy"}, {"word":"Good-den"}, {"word":"Gramercy"}, {"word":"Ha"}, {"word":"Hah"}, {"word":"Harrow"}, {"word":"Heartlings"}, {"word":"Heigh-ho"}, {"word":"Hem"}, {"word":"Hey"}, {"word":"Hey"}, {"word":"Heyday"}, {"word":"Hip"}, {"word":"Hist"}, {"word":"Ho"}, {"word":"Hoa"}, {"word":"Ho"}, {"word":"Hoa"}, {"word":"Hoa"}, {"word":"Holla"}, {"word":"Hollo"}, {"word":"Hollow"}, {"word":"Hoo"}, {"word":"Hoo"}, {"word":"Hoy"}, {"word":"Hullo"}, {"word":"Hum"}, {"word":"Hum"}, {"word":"Hum"}, {"word":"Humph"}, {"word":"Hurrah"}, {"word":"Hurra"}, {"word":"Huzza"}, {"word":"Jossa"}, {"word":"La"}, {"word":"La"}, {"word":"Lack"}, {"word":"Lackadaisy"}, {"word":"Lackaday"}, {"word":"Law"}, {"word":"Lo"}, {"word":"Marie"}, {"word":"Marry"}, {"word":"Mary"}, {"word":"Mum"}, {"word":"O"}, {"word":"Ods"}, {"word":"Off"}, {"word":"Oh"}, {"word":"Oho"}, {"word":"Out"}, {"word":"Oyez"}, {"word":"Pah"}, {"word":"Parfay"}, {"word":"Pish"}, {"word":"Poh"}, {"word":"Pooh"}, {"word":"Prithee"}, {"word":"Proface"}, {"word":"Prythee"}, {"word":"Pshaw"}, {"word":"Pugh"}, {"word":"Puh"}, {"word":"Quits"}, {"word":"Quotha"}, {"word":"Roint"}, {"word":"Salve"}, {"word":"'Sblood"}, {"word":"Scat"}, {"word":"'Sdeath"}, {"word":"Sessa"}, {"word":"Shoo"}, {"word":"Shough"}, {"word":"Silence"}, {"word":"'Snails"}, {"word":"So"}, {"word":"Soft"}, {"word":"Soho"}, {"word":"'Swounds"}, {"word":"Tush"}, {"word":"Ugh"}, {"word":"Walaway"}, {"word":"Waly"}, {"word":"Wayleway"}, {"word":"Welaway"}, {"word":"Welladay"}, {"word":"Weyleway"}, {"word":"Whist"}, {"word":"Whoa"}, {"word":"Yoicks"}, {"word":"Zounds"}]
